name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_NAME: PixelPerfectJump

jobs:
  build:
    runs-on: arc-runner-set

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update -y
          sudo apt install -y curl git build-essential p7zip-full wget
          sudo mkdir /usr/share/dotnet
          sudo chmod 777 /usr/share/dotnet
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Download Dalamud
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/net7/latest.zip -O /tmp/latest.zip
          sudo 7z x -o/tmp/dalamud /tmp/latest.zip
          sudo rm /tmp/latest.zip

      - name: Build
        run: |
          sudo dotnet restore
          sudo dotnet build --configuration Release --nologo --output /tmp/bin/
        env:
          DOTNET_CLI_TELEMETRY_OUTPUT: true

      - name: Create artifact
        run: |
          sudo 7z a /tmp/bin/* /tmp/PixelPerfectJump.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: /tmp/PixelPerfectJump.zip
