name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
    - '*'
  pull_request:
    branches: [main]

env:
  PROJECT_NAME: PixelPerfectJump

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/net7/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Build
        run: |
          dotnet restore
          dotnet build --configuration Release --nologo --output bin/
        env:
          DOTNET_CLI_TELEMETRY_OUTPUT: true

      - name: Create artifact
        run: |
          Compress-Archive -Path "bin/*" -DestinationPath PixelPerfectJump.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: PixelPerfectJump.zip
          asset_name: PixelPerfectJump.zip
          asset_content_type: application/zip
